#!/usr/bin/env python3

import os
import sys

import yaml

sys.path.append(os.path.dirname(__file__) + '/../common')

from crunchyclient import CrunchyCLIClient

if 'CVCONFIG' in os.environ:
    conffile = os.environ['CVCONFIG']
else:
    conffile = os.path.expanduser('~/.config/crunchyvicar/cliclient.yml')

with open(conffile, 'r') as f:
    config = yaml.load(f.read(), Loader=yaml.SafeLoader)

client = CrunchyCLIClient(config)
client.run(*sys.argv[1:])
