---
api:
  url: "http://localhost:5555"
schema:
  root_uuid: "02331837-798c-44b5-92a1-a316ee9b617f"
  keys:
  - Resource
  - type
  - label
  - Person
  - age
  - firstname
  - lastname
volumes:
  testvol:
    path: /home/arjen
    exclude:
    - /home/arjen/.cache
    - /home/arjen/.mozilla
